# Generated by Django 4.2.4 on 2023-09-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='referral_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='referrer',
        ),
    ]
