# Generated by Django 4.2.4 on 2023-09-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
