# Generated by Django 4.2.4 on 2023-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='product_images',
        ),
        migrations.AddField(
            model_name='category',
            name='category_images',
            field=models.ImageField(blank=True, upload_to='photos/categories'),
        ),
    ]
