# Generated by Django 4.2.4 on 2023-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='photos/product'),
        ),
    ]
