# Generated by Django 4.2.4 on 2023-08-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_stock_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
