# Generated by Django 4.2.2 on 2023-08-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
