# Generated by Django 4.2.4 on 2023-09-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
