# Generated by Django 4.2.4 on 2023-09-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0007_alter_coupons_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
