# Generated by Django 4.2.4 on 2023-09-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_coupons_soft_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='soft_deleted',
        ),
    ]
