# Generated by Django 4.2.4 on 2023-09-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0009_remove_coupons_soft_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
