from django.urls import path
from userapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('product_list/', views.product_list, name='product_list'),
    path('product_detail/<int:category_id>/<int:product_id>/', views.product_detail, name='product_detail'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('user_login/', views.user_login, name='user_login'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_validation/<uidb64>/<token>/', views.password_validation, name='password_validation'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('order_details/<int:order_id>/', views.order_details, name='order_details'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('return_order/<int:order_id>/', views.return_order, name='return_order'),
    path('add_address/', views.add_address, name='add_address'),
    path('manage_address/', views.manage_address, name='manage_address'),
    path('edit_address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('delete_address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('my_coupons/', views.my_coupons, name='my_coupons'),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('view_wishlist/', views.view_wishlist, name='view_wishlist'),
    path('remove_from_wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('my_wallet/', views.my_wallet, name='my_wallet'),
    path('wallet_pay/<int:order_id>/', views.wallet_pay, name='wallet_pay'),
    path('order_invoice/<int:order_id>/', views.order_invoice, name='order_invoice'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('search/', views.search, name='search'),
]
